//
// Created by xilef on 10/29/2025.
//

#ifndef SESSION1OBSTACLECOURSE_MOVEACCROSSHOLE_H
#define SESSION1OBSTACLECOURSE_MOVEACCROSSHOLE_H

void MoveAccrossHole();
#endif //SESSION1OBSTACLECOURSE_MOVEACCROSSHOLE_H