//
// Created by xilef on 10/29/2025.
//

#ifndef SESSION1DANCINGROBOT_OBSTACLEDESTROYTARGET_H
#define SESSION1DANCINGROBOT_OBSTACLEDESTROYTARGET_H
void DestroyTarget();
float TurnUntilAdvance();

#endif //SESSION1DANCINGROBOT_OBSTACLEDESTROYTARGET_H